import './globals.css';
import { GlobalProvider } from './context/GlobalContext';
import { ClerkProvider } from '@clerk/nextjs';
import Providers from './providers';
import { clerkAppearance } from './lib/clerkAppearance';
import { Analytics } from '@vercel/analytics/next';

export const metadata = {
  title: 'Fluentor Agent',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <GlobalProvider>
          <Providers>
            <ClerkProvider appearance={clerkAppearance}>
              {children}
              <Analytics />
            </ClerkProvider>
          </Providers>
        </GlobalProvider>
      </body>
    </html>
  );
}
